name: Deploy Static HTML with Secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy src to dist
      run: mkdir dist && cp -r src/* dist/

    - name: Replace __WORKER_URL__ in HTML
      run: |
        find dist -type f -name "*.html" -exec sed -i "s|__WORKER_URL__|${{ secrets.WORKER_URL }}|g" {} +

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
