name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace __WORKER_URL__ with secret
      run: |
        find . -type f -name "*.html" -exec sed -i "s|__WORKER_URL__|${{ secrets.WORKER_URL }}|g" {} +

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # root of repo or change if using `dist/`
